local opt = vim.opt
opt.autoindent = true
opt.shiftwidth = 4 -- autoindent size
opt.expandtab = true -- タブ文字の代わりにスペースを使用
opt.tabstop = 4 -- タブ文字が表示される幅
opt.softtabstop = -1 -- refer to tabstop
opt.ignorecase = true
opt.smartcase = true -- 大文字を含む検索でignorecaseをfalse
opt.mouse = "a"
opt.number = true
opt.relativenumber = true
opt.cursorline = true
